"""Generated battles to their consumers: the game's battle file, config/nn/arenas.json's format
and the simulator's army descriptions.

    export.scenario_xml(arena, defender="enemy")     # tools/nn/scenario.py
    export.write_arenas(arenas, path)                # {"arenas": {name: entry}}, as config/nn/arenas.json
    export.to_sim(arenas, own_ai="attack")           # [description] for tools/nn/sim/scenario.build (torch)
"""
import json
import tempfile
from pathlib import Path

from tools.nn import scenario as arena_scenario


def entry(arena):
    """A generated arena as a named arena of config/nn/arenas.json (the map is the base's)."""
    return {k: v for k, v in arena.items() if k not in arena_scenario.BASE_ONLY + ("name",)}


def write_arenas(arenas, path):
    doc = {"description": "Generated by tools/nn/armies (random battles).",
           "arenas": {a["name"]: entry(a) for a in arenas}}
    Path(path).write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8", newline="\n")
    return path


def scenario_xml(arena, defender="enemy"):
    return arena_scenario.scenario_xml(arena, defender)


def to_sim(arenas, own_ai="attack"):
    """Simulator army descriptions (tools/nn/sim/scenario.from_arena) of generated arenas."""
    from tools.nn.sim import scenario as sim_scenario
    names = [a["name"] for a in arenas]
    assert len(set(names)) == len(names), "arena names must be unique"
    with tempfile.TemporaryDirectory() as tmp:
        path = write_arenas(arenas, Path(tmp) / "arenas.json")
        return [sim_scenario.from_arena(n, own_ai, arena_path=path) for n in names]
