"""Build a deterministic, uncompressed PFH5 Mod pack containing our Lua only.

Format reference: RPFM rpfm_lib/src/files/pack/pack_versions/pfh5.rs.
Pack utility supports explicit dependency names; active builds use the pinned True Sight profile.
Standalone packing also freezes the required mod; legacy launchers remain retired.
"""
from pathlib import Path
import argparse
import hashlib
import importlib.util
import json
import struct

ROOT = Path(__file__).resolve().parents[1]
PACK_NAME = "tww3_bai_duel.pack"
ENTRY = "script\\battle\\mod\\tww3_bai_duel.lua"


def pack_files(files: dict[str, bytes], dependencies=("true_sight.pack",)) -> bytes:
    dependencies = tuple(dependencies)
    if len(set(dependencies)) != len(dependencies) or any(not n.endswith('.pack') or not n.isascii() or any(c in n for c in '/\\\x00') or '..' in n for n in dependencies):
        raise ValueError('invalid pack dependencies')
    dependency_index = b''.join(n.encode('ascii') + b'\0' for n in dependencies)
    index, payload = bytearray(), bytearray()
    for name, content in sorted(files.items()):
        if not name.isascii() or ".." in name or name.startswith(("/", "\\")):
            raise ValueError("pack paths must be relative ASCII paths")
        index += struct.pack("<IB", len(content), 0) + name.encode("ascii") + b"\0"
        payload += content
    return struct.pack("<4s6I", b"PFH5", 3, len(dependencies), len(dependency_index), len(files), len(index), 0) + dependency_index + index + payload


def read_pack(blob: bytes) -> dict[str, bytes]:
    magic, kind, deps, dep_size, count, index_size, timestamp = struct.unpack_from("<4s6I", blob)
    if (magic, kind, timestamp) != (b"PFH5", 3, 0):
        raise ValueError("unexpected pack header")
    dependency_index = blob[28:28 + dep_size]
    if dependency_index.count(b'\0') != deps or (dep_size and not dependency_index.endswith(b'\0')):
        raise ValueError('invalid dependency index')
    pos, data = 28 + dep_size, 28 + dep_size + index_size
    entries = {}
    for _ in range(count):
        size, compressed = struct.unpack_from("<IB", blob, pos)
        pos += 5
        end = blob.index(0, pos)
        name = blob[pos:end].decode("ascii")
        if compressed or name in entries or data + size > len(blob):
            raise ValueError("invalid pack entry")
        entries[name] = blob[data:data + size]
        pos, data = end + 1, data + size
    if pos != 28 + dep_size + index_size or data != len(blob):
        raise ValueError("pack length mismatch")
    return entries


def build(runs=1, speed=1, timeout_s=600, scenario="ranged_melee"):
    spec = importlib.util.spec_from_file_location("required_mod", ROOT / "tools/competition/dependencies.py")
    dependency = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(dependency)
    lock, dependency_files = dependency.freeze_inputs({"mod_profile": "true-sight-v1"})
    if scenario not in ("ranged_melee", "triple_melee"):
        raise ValueError("unsupported scenario")
    if scenario == "triple_melee":
        runs = 3
    config = dict(runs=runs, speed=speed, timeout_ms=timeout_s * 1000, tick_ms=1000, scenario=scenario)
    harness = (ROOT / ("src/arena.lua" if scenario == "triple_melee" else "src/harness.lua")).read_text(encoding="utf-8")
    policy = (ROOT / "src/policy.lua").read_text(encoding="utf-8")
    scenario_lua = (ROOT / "src/scenario.lua").read_bytes()
    scenario_xml = (ROOT / f"scenarios/{scenario}.xml").read_bytes()
    digest = hashlib.sha256((harness + policy + json.dumps(config, sort_keys=True)).encode() + scenario_lua + scenario_xml).hexdigest()
    config["build"] = digest[:16]
    lua_config = "{ " + ", ".join(f"{k} = {json.dumps(v)}" for k, v in config.items()) + " }"
    script = (
        "-- Generated by tools/build.py. Edit src/, not this file.\n"
        "local harness = (function()\n" + harness + "\nend)()\n"
        "local policy = (function()\n" + policy + "\nend)()\n"
        "if bm then harness.attach(bm, " + lua_config + ", policy) end\n"
    ).encode("utf-8")
    files = {
        ENTRY: script,
        "script\\battle\\tww3_bai\\scenario.lua": scenario_lua,
        f"script\\battle\\tww3_bai\\{scenario}.xml": scenario_xml,
    }
    blob = pack_files(files)
    assert read_pack(blob) == files
    target = ROOT / "build"
    target.mkdir(exist_ok=True)
    for name, data in dependency_files.items():
        destination = target / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
    (target / PACK_NAME).write_bytes(blob)
    (target / "tww3_bai_duel.lua").write_bytes(script)
    (target / "tww3_bai_policy.lua").write_bytes(policy.encode("utf-8"))
    manifest = dict(mod_dependencies=lock, config=config, pack=PACK_NAME, pack_sha256=hashlib.sha256(blob).hexdigest(), entries=list(files), engine_tested=False)
    (target / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", type=int, choices=range(1, 11), default=3)
    parser.add_argument("--speed", type=int, choices=(1, 3, 10, 20), default=20)
    parser.add_argument("--timeout", type=int, default=600, help="model seconds, 30..1800")
    parser.add_argument("--scenario", choices=("ranged_melee", "triple_melee"), default="ranged_melee")
    args = parser.parse_args()
    if not 30 <= args.timeout <= 1800:
        parser.error("--timeout must be between 30 and 1800 seconds")
    print(json.dumps(build(args.runs, args.speed, args.timeout, args.scenario), indent=2))
