"""Scenario and config for src/entries/archer_range.lua: when do archers start
shooting, and does the depth of their block matter (user, 28.09.2026)?

Four lanes 200 m apart on The Moorlands Route (south, open ground); in each an
Empire archer unit at its own width — 60, 30, 15 and 8 m, so 7.9 to 46.3 m deep
(data/roster) — and one Empire spearmen unit in front of it as the target.

Mode "damage" (user, 28.09.2026: how much damage arrows deal and take):
archers 20 m wide (18 m deep) in every lane, the target (spearmen 30 m wide)
at its own distance, fearless; they shoot until out of arrows. DAMAGE_MID_M:
from the archers' middle to the target's front rank.
"""
import re

from tools import config as project
from tools import roster

ARCHERS, SPEARMEN, GENERAL = "wh2_dlc13_emp_inf_archers_0", "wh_main_emp_inf_spearmen_0", "wh_main_emp_cha_general_0"
LANES = [(-350, 60), (-150, 30), (50, 15), (250, 8)]
Z0 = -450  # the archers' front rank
SCENARIO = project.SCENARIOS / "archer_range.xml"
DAMAGE_WIDTH, DAMAGE_DEPTH = 20, 18.0
DAMAGE_MID_M = [120, 105, 90, 70]

UNIT = """      <unit num_soldiers="{men}" script_name="{script_name}">
        <unit_type type="{key}"/>
        <position x="{x}" y="{z}"/><orientation radians="0"/><width metres="10"/>
        <unit_experience level="0"/>
{general}      </unit>
"""
AREA_RE = re.compile(r"      <deployment_area>.*?</deployment_area>\n", re.S)
ROSTER_NOTE = ("Generated by tools/roster.py from config/roster/capture.json. Edit the\n"
               "     list there, not this file. Side 1: units whose card and formation are\n"
               "     read (src/entries/roster_capture.lua). Side 2: a general held by script\n"
               "     far away, only because a battle needs two armies.")
NOTE = ("Generated by tools/archer_range.py. Edit that file, not this one. Side 1:\n"
        "     the archers of every lane and a lord; side 2: their targets and a lord\n"
        "     (src/entries/archer_range.lua).")


def scenario_xml(sides, faction="wh_main_emp_empire"):
    """Both armies on the roster scenario's frame (tools/roster.SCENARIO_HEAD) with no
    deployment areas. sides = {"own": [...], "enemy": [...]}, a unit = {script_name,
    key, men, general, x, z}."""
    head = roster.SCENARIO_HEAD
    own_part, rest = head.split('  <alliance id="1">', 1)
    head = AREA_RE.sub("", own_part, count=1) + '  <alliance id="1">' + rest
    blocks = {side: "".join(UNIT.format(
        men=int(u["men"]), script_name=u["script_name"], key=u["key"], x=u["x"], z=u["z"],
        general=f'        <general><name>{side}</name><star_rating level="1"/></general>\n' if u["general"] else "")
        for u in units) for side, units in sides.items()}
    # The enemy alliance is a copy of ours with its own units and rout point.
    enemy = head[head.index('  <alliance id="0">'):head.index('  <alliance id="1">')]
    enemy = enemy.replace('<alliance id="0">', '<alliance id="1">') \
        .replace('<rout_position x="600" y="0"/>', '<rout_position x="-600" y="0"/>') \
        .replace("{units}", blocks["enemy"])
    start = head.index('  <alliance id="1">')
    end = head.index("  </alliance>", start) + len("  </alliance>\n")
    text = (head[:start] + enemy + head[end:]).replace(ROSTER_NOTE, NOTE)
    return text.format(faction=faction, units=blocks["own"])


def write_scenario():
    own = [{"script_name": f"arc_{i}", "key": ARCHERS, "men": 90, "general": False, "x": x, "z": Z0 - 60}
           for i, (x, _) in enumerate(LANES, start=1)]
    own.append({"script_name": "own_general", "key": GENERAL, "men": 1, "general": True, "x": -450, "z": -150})
    enemy = [{"script_name": f"tgt_{i}", "key": SPEARMEN, "men": 120, "general": False, "x": x, "z": Z0 + 200}
             for i, (x, _) in enumerate(LANES, start=1)]
    enemy.append({"script_name": "enemy_general", "key": GENERAL, "men": 1, "general": True, "x": 450, "z": 100})
    SCENARIO.write_text(scenario_xml({"own": own, "enemy": enemy}), encoding="utf-8")


def run_config(mode, rotate=0):
    """Entry config and the longest model length in seconds. rotate: damage mode, the
    distances shifted by that many lanes (the same distance on other ground)."""
    if mode == "damage":
        mids = DAMAGE_MID_M[rotate % 4:] + DAMAGE_MID_M[:rotate % 4]
        config = {"mode": mode, "z0": Z0, "start_d": 0, "end_d": 0, "step_m": 0, "step_ticks": 1, "after_ticks": 0,
                  "idle_ticks": 30,
                  "lanes": [{"archer": f"arc_{i}", "target": f"tgt_{i}", "width": DAMAGE_WIDTH, "x": x,
                             "d": mid - DAMAGE_DEPTH / 2}
                            for i, ((x, _), mid) in enumerate(zip(LANES, mids), start=1)],
                  "held": [{"side": 1, "name": "own_general"}, {"side": 2, "name": "enemy_general"}]}
        return config, 420
    config = {"mode": mode, "z0": Z0, "start_d": 170, "end_d": 40, "step_m": 2, "step_ticks": 2, "after_ticks": 10,
              "lanes": [{"archer": f"arc_{i}", "target": f"tgt_{i}", "width": w, "x": x}
                        for i, (x, w) in enumerate(LANES, start=1)],
              "held": [{"side": 1, "name": "own_general"}, {"side": 2, "name": "enemy_general"}]}
    model_s = (170 - 40) / 2 * 2 + 60 if mode == "fire_at_will" else 180
    return config, model_s
