"""Build a battle pack from src/ for one target. Never touches the game.

Usage:
    python -m tools.build duel --runs 3 --speed 20 --timeout 300
    python -m tools.build arena
    python -m tools.build ai-vs-ai --speed 3
    python -m tools.build map-capture --step 3 --features

Output: build/<target>/ with the .pack, the bundled script and manifest.json.
Install and launch with tools/launcher/launch.ps1.
"""
import argparse
import hashlib
import json
import sys

from tools import config as project
from tools.pack import bundle, pfh5

# target -> entry module, pack/script names, scenario XML and its in-pack name.
TARGETS = {
    "duel": {
        "entry": "entries.duel",
        "pack": "tww3_bai_duel.pack",
        "script": "tww3_bai_duel",
        "folder": "tww3_bai",
        "scenario": "ranged_melee.xml",
        "packed_scenario": "ranged_melee.xml",
    },
    "arena": {
        "entry": "entries.arena",
        "pack": "tww3_bai_arena.pack",
        "script": "tww3_bai_arena",
        "folder": "tww3_bai",
        "scenario": "triple_melee.xml",
        "packed_scenario": "triple_melee.xml",
    },
    "ai-vs-ai": {
        "entry": "entries.ai_vs_ai",
        "pack": "tww3_bai_ai_vs_ai.pack",
        "script": "tww3_bai_ai_vs_ai",
        "folder": "tww3_bai",
        "scenario": "ai_vs_ai.xml",
        "packed_scenario": "ai_vs_ai.xml",
    },
    "map-capture": {
        "entry": "entries.map_capture",
        "pack": "tww3_bai_map_capture.pack",
        "script": "tww3_bai_map_capture",
        "folder": "tww3_bai_map_capture",
        "scenario": "map_capture.xml",
        "packed_scenario": "map_probe.xml",
    },
}

SCENARIO_LUA = b"load_script_libraries()\n"


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def check_syntax(script):
    """Compiles the bundle with Lua 5.1 (lupa) when available."""
    try:
        from lupa.lua51 import LuaRuntime
    except ImportError:
        return False
    LuaRuntime().eval("function(s) local f, e = loadstring(s); assert(f, e) end")(script)
    return True


def build(target, run_config, dependencies=()):
    spec = TARGETS[target]
    scenario_xml = (project.SCENARIOS / spec["scenario"]).read_bytes()
    # The build id covers every input, so telemetry rows name the exact code.
    probe_script, modules = bundle.bundle(project.SRC, spec["entry"], run_config)
    digest = sha256(probe_script.encode("utf-8") + scenario_xml)[:16]
    run_config = dict(run_config, build=digest)
    header = f"-- Generated by tools/build.py ({target}, build {digest}). Edit src/, not this file.\n"
    script, _ = bundle.bundle(project.SRC, spec["entry"], run_config, header)
    script_bytes = script.encode("utf-8")
    syntax_checked = check_syntax(script)

    folder = spec["folder"]
    files = {
        f"script\\battle\\mod\\{spec['script']}.lua": script_bytes,
        f"script\\battle\\{folder}\\scenario.lua": SCENARIO_LUA,
        f"script\\battle\\{folder}\\{spec['packed_scenario']}": scenario_xml,
    }
    dependency_names = [d["pack"] for d in dependencies]
    blob = pfh5.pack_files(files, dependency_names)
    assert pfh5.read_pack(blob) == (files, tuple(dependency_names))

    out = project.BUILD / target
    out.mkdir(parents=True, exist_ok=True)
    (out / spec["pack"]).write_bytes(blob)
    (out / f"{spec['script']}.lua").write_bytes(script_bytes)
    manifest = {
        "target": target,
        "build": digest,
        "config": run_config,
        "modules": modules,
        "pack": spec["pack"],
        "pack_sha256": sha256(blob),
        "entries": list(files),
        "scenario": f"script/battle/{folder}/{spec['packed_scenario']}",
        "dependencies": list(dependencies),
        "syntax_checked": syntax_checked,
        "engine_tested": False,
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("target", choices=sorted(TARGETS))
    parser.add_argument("--runs", type=int, choices=range(1, 11), default=3, help="duel: battles in a row")
    parser.add_argument("--speed", type=int, choices=(1, 3, 10, 20), default=20)
    parser.add_argument("--timeout", type=int, default=600, help="model seconds, 30..1800")
    parser.add_argument("--tick-ms", type=int, default=1000)
    parser.add_argument("--step", type=int, choices=(1, 2, 3, 5), default=5, help="map-capture: cell size, m")
    parser.add_argument("--features", action="store_true",
                        help="map-capture: also read objects and reachability after deployment")
    args = parser.parse_args(argv)
    if not 30 <= args.timeout <= 1800:
        parser.error("--timeout must be between 30 and 1800 seconds")

    if args.target == "map-capture":
        run_config = {"step": args.step, "features": args.features}
    else:
        run_config = {"runs": args.runs if args.target == "duel" else 1, "speed": args.speed,
                      "timeout_ms": args.timeout * 1000, "tick_ms": args.tick_ms,
                      "scenario": TARGETS[args.target]["scenario"].removesuffix(".xml")}
    manifest = build(args.target, run_config, project.load().get("dependencies", []))
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
