"""Scenarios for the enemy-layout runs: the game AI deploys a given army.

    python -m tools.enemy_layout list
    python -m tools.build enemy-layout --layout balanced_5

config/armies/defender_layouts.json lists the layouts. Our army (side 1) is
held by script in its zone; the enemy (side 2) is left to the game AI in the
other zone. Spawn points are a plain grid: the game AI redeploys its army when
deployment ends (measured 26.09.2026), so they do not steer the result.
"""
import argparse
import json
import sys
from xml.sax.saxutils import escape

from tools import config as project

CONFIG = project.CONFIG_DIR / "armies" / "defender_layouts.json"
SCENARIO = project.SCENARIOS / "enemy_layout.xml"

HEAD = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/enemy_layout.py from config/armies/defender_layouts.json
     (layout {layout}). Side 1: our army, held by script. Side 2: the game AI. -->
<battle>
{alliances}  <battle_description>
    <time_of_day>day</time_of_day>
    <season>Spring</season>
    <precipitation_type>dry</precipitation_type>
    <battle_script prepare_for_fade_in="false">script/battle/tww3_bai/scenario.lua</battle_script>
    <type>classic</type>
    <duration>86400</duration>
    <los_visibility_enabled>true</los_visibility_enabled>
  </battle_description>
  <weather>
    <prevailing_wind x="1" y="0"/>
    <environment_key>weather/battle/wh_day_desert_02.environment</environment_key>
  </weather>
  <sea_surface_name>wind_level_0</sea_surface_name>
  <battle_map_definition>
    <name>terrain\\battles\\wh3_dlc21_macro_emp_grasslands_01\\</name>
    <catchment_area>catchment_03</catchment_area>
    <tile_map_position x="0.5" y="0.5"/>
  </battle_map_definition>
</battle>
"""

ALLIANCE = """  <alliance id="{id}">
    <army>
      <faction>{faction}</faction>
      <deployment_area>
        <centre x="{x}" y="{z}"/><width metres="{side}"/><height metres="{side}"/><orientation radians="{zone_turn}"/>
      </deployment_area>
      <camera_start_position x="80" y="700" z="-450"/>
      <camera_target_position x="80" y="530" z="-100"/>
{units}    </army>
    <victory_condition><kill_or_rout_enemy_ignore_reinforcements/></victory_condition>
    <rout_position x="{rout_x}" y="0"/>
  </alliance>
"""

UNIT = """      <unit num_soldiers="{men}" script_name="{name}">
        <unit_type type="{key}"/>
        <position x="{x}" y="{z}"/><orientation radians="{turn}"/><width metres="{width}"/>
        <unit_experience level="0"/>
{general}      </unit>
"""


def load(path=CONFIG):
    return json.loads(path.read_text(encoding="utf-8"))


def men_of(key):
    entry = json.loads((project.ROOT / "data" / "roster" / f"{key}.json").read_text(encoding="utf-8"))
    return entry["card"]["profile"]["initial_number_of_men"]


def unit_rows(units, prefix, zone, facing_north):
    """A plain grid of spawn points inside the zone, 5 per row, 40 m apart."""
    rows, i = [], 0
    for item in units:
        men = men_of(item["key"])
        for _ in range(item["count"]):
            col, row = i % 5, i // 5
            x = zone["x"] + (col - 2) * 40
            z = zone["z"] + (row - 1) * 40 * (1 if facing_north else -1)
            general = men == 1 and item["key"].endswith("_cha_general_0")
            rows.append(UNIT.format(
                men=men, name=f"{prefix}_{i + 1}", key=escape(item["key"]), x=x, z=z,
                turn=0 if facing_north else 3.14159265359, width=5 if men == 1 else 30,
                general=f'        <general><name>{prefix}</name><star_rating level="1"/></general>\n'
                if general else ""))
            i += 1
    return "".join(rows)


def scenario_xml(spec, layout):
    assert layout in spec["layouts"], f"unknown layout {layout}; see python -m tools.enemy_layout list"
    units = spec["layouts"][layout]
    assert sum(u["count"] for u in units) <= 20, "an army holds at most 20 units"
    own, enemy = spec["own"], spec["enemy_zone"]
    alliances = (
        ALLIANCE.format(id=0, faction=spec["faction"], x=own["zone"]["x"], z=own["zone"]["z"],
                        side=own["zone"]["side"], zone_turn=4.71, rout_x=600,
                        units=unit_rows(own["units"], "own", own["zone"], True))
        + ALLIANCE.format(id=1, faction=spec["faction"], x=enemy["x"], z=enemy["z"], side=enemy["side"],
                          zone_turn=1.57, rout_x=-600, units=unit_rows(units, "enemy", enemy, False)))
    return HEAD.format(layout=layout, alliances=alliances)


def write_scenario(layout, spec=None):
    spec = spec or load()
    SCENARIO.write_text(scenario_xml(spec, layout), encoding="utf-8")
    return spec


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["list"])
    parser.parse_args(argv)
    for name, units in load()["layouts"].items():
        print(name, sum(u["count"] for u in units), "units")
    return 0


if __name__ == "__main__":
    sys.exit(main())
