"""Unit roster: data/roster/<unit key>.json, one file per unit type.

    python -m tools.roster scenario            # scenarios/roster_capture.xml from config/roster/capture.json
    python -m tools.roster update <events.jsonl>
    python -m tools.roster show [--markdown]

A roster file has four parts:
  card       the unit card from battle (roster-capture run): stats, details, profile
  formation  our measurement: ordered width -> front x depth, reform time
  ours       filled by hand: fire type (arc / direct), roles, notes
  battle     later: results checked in battles
`update` rewrites only `card` and `formation`; `ours` and `battle` are kept.
"""
import argparse
import json
import sys
from pathlib import Path
from xml.sax.saxutils import escape

from tools import config as project
from tools.analysis.move_probe import geometry

ROSTER = project.ROOT / "data" / "roster"
CAPTURE = project.CONFIG_DIR / "roster" / "capture.json"
SCENARIO = project.SCENARIOS / "roster_capture.xml"
FIRE_TYPES = ("arc", "direct", None)

SCENARIO_HEAD = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/roster.py from config/roster/capture.json. Edit the
     list there, not this file. Side 1: units whose card and formation are
     read (src/entries/roster_capture.lua). Side 2: a general held by script
     far away, only because a battle needs two armies. -->
<battle>
  <alliance id="0">
    <army>
      <faction>{faction}</faction>
      <deployment_area>
        <centre x="0" y="0"/><width metres="900"/><height metres="900"/><orientation radians="4.71"/>
      </deployment_area>
      <camera_start_position x="100" y="700" z="-400"/>
      <camera_target_position x="100" y="530" z="-120"/>
{units}    </army>
    <victory_condition><kill_or_rout_enemy_ignore_reinforcements/></victory_condition>
    <rout_position x="600" y="0"/>
  </alliance>
  <alliance id="1">
    <army>
      <faction>{faction}</faction>
      <deployment_area>
        <centre x="0" y="0"/><width metres="900"/><height metres="900"/><orientation radians="1.57"/>
      </deployment_area>
      <camera_start_position x="100" y="700" z="-400"/>
      <camera_target_position x="100" y="530" z="-120"/>
      <unit num_soldiers="1" script_name="far_general">
        <unit_type type="wh_main_emp_cha_general_0"/>
        <position x="300" y="-400"/><orientation radians="1.57079632679"/><width metres="5"/>
        <unit_experience level="0"/>
        <general><name>Far away</name><star_rating level="1"/></general>
      </unit>
    </army>
    <victory_condition><kill_or_rout_enemy_ignore_reinforcements/></victory_condition>
    <rout_position x="-600" y="0"/>
  </alliance>
  <battle_description>
    <time_of_day>day</time_of_day>
    <season>Spring</season>
    <precipitation_type>dry</precipitation_type>
    <battle_script prepare_for_fade_in="false">script/battle/tww3_bai/scenario.lua</battle_script>
    <type>classic</type>
    <duration>86400</duration>
    <los_visibility_enabled>true</los_visibility_enabled>
  </battle_description>
  <weather>
    <prevailing_wind x="1" y="0"/>
    <environment_key>weather/battle/wh_day_desert_02.environment</environment_key>
  </weather>
  <sea_surface_name>wind_level_0</sea_surface_name>
  <battle_map_definition>
    <name>terrain\\battles\\wh3_dlc21_macro_emp_grasslands_01\\</name>
    <catchment_area>catchment_03</catchment_area>
    <tile_map_position x="0.5" y="0.5"/>
  </battle_map_definition>
</battle>
"""


def load_capture(path=None):
    """config/roster/capture.json with script names and slots assigned."""
    spec = json.loads(Path(path or CAPTURE).read_text(encoding="utf-8"))
    units = spec["units"]
    assert units, "capture list is empty"
    assert len(units) <= len(spec["slots"]), "more units than slots in config/roster/capture.json"
    assert len({u["key"] for u in units}) == len(units), "a unit key is listed twice"
    assert sum(1 for u in units if u.get("general")) <= 1, "at most one general per capture"
    for i, (unit, slot) in enumerate(zip(units, spec["slots"]), start=1):
        unit["script_name"] = f"roster_{i}"
        unit["slot"] = {"x": slot[0], "z": slot[1]}
    return spec


def scenario_xml(spec):
    rows = []
    for u in spec["units"]:
        general = '        <general><name>Roster</name><star_rating level="1"/></general>\n' if u.get("general") else ""
        width = 5 if u["men"] == 1 else spec["baseline_width"]
        rows.append(
            f'      <unit num_soldiers="{int(u["men"])}" script_name="{u["script_name"]}">\n'
            f'        <unit_type type="{escape(u["key"])}"/>\n'
            f'        <position x="{u["slot"]["x"]}" y="{u["slot"]["z"]}"/><orientation radians="0"/>'
            f'<width metres="{width}"/>\n'
            f'        <unit_experience level="0"/>\n{general}'
            f'      </unit>\n')
    return SCENARIO_HEAD.format(faction=escape(spec["faction"]), units="".join(rows))


def write_scenario(spec=None):
    spec = spec or load_capture()
    SCENARIO.write_text(scenario_xml(spec), encoding="utf-8")
    return spec


def run_config(spec, speed, settle_ms):
    """Entry config for src/entries/roster_capture.lua and its longest length in model seconds."""
    widths = spec["widths"]
    model_s = len(widths) * (spec["shape_timeout_s"] + settle_ms / 1000)
    return {"widths": widths, "baseline_width": spec["baseline_width"], "shape_timeout_s": spec["shape_timeout_s"],
            "settle_ms": settle_ms, "speed": speed,
            "units": [{"script_name": u["script_name"], "key": u["key"], "slot": u["slot"]} for u in spec["units"]]}, model_s


def _stats(card):
    stats = card.get("stats") or {}
    if stats.get("status") != "ok":
        return {"unavailable": stats.get("reason", "missing")}
    return {row["key"]: {"value": row.get("Value"), "displayed": row.get("DisplayedValue"), "base": row.get("ValueBase")}
            for row in stats["list"] if isinstance(row.get("key"), str) and not row["key"].startswith("unknown:")}


def _shape(row):
    if not row.get("soldiers_dm"):
        return {"ordered_m": row["width"], "unavailable": row.get("soldiers_unavailable")}
    g = geometry(row)
    last_moving = row.get("last_moving_ms")
    return {"ordered_m": row["width"], "front_m": round(g["width_m"], 1), "depth_m": round(g["depth_m"], 1),
            "reform_s": None if last_moving is None else round(last_moving / 1000 + 1, 1),
            "ended": row["reason"], "men": len(row["soldiers_dm"]) // 2}


def update(events_path, roster_dir=ROSTER):
    rows = [json.loads(line) for line in Path(events_path).read_text(encoding="utf-8").splitlines() if line.strip()]
    ready = next(r for r in rows if r["event"] == "ready")
    stamp = {"date": ready["wall_iso"][:10], "game_version": ready.get("game_version"), "build": ready.get("build"),
             "run": ready["batch"]}
    roster_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for card in (r for r in rows if r["event"] == "unit_card"):
        path = roster_dir / f"{card['key']}.json"
        old = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
        shapes = [_shape(r) for r in rows if r["event"] == "shape_result" and r["key"] == card["key"]]
        entry = {
            "key": card["key"],
            "card": dict(stamp, profile=card["profile"], details=card["details"], stats=_stats(card)),
            "formation": dict(stamp, widths=sorted(shapes, key=lambda s: -s["ordered_m"])) if shapes else
            old.get("formation", {"widths": [], "note": "single entity: no ranks"}),
            "ours": old.get("ours", {"fire": None, "roles": [], "notes": ""}),
            "battle": old.get("battle", {}),
        }
        path.write_text(json.dumps(entry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        written.append(path)
    return written


def load_roster(roster_dir=ROSTER):
    return [json.loads(p.read_text(encoding="utf-8")) for p in sorted(roster_dir.glob("*.json"))]


def check(entries):
    """Hand-filled fields must be valid."""
    for e in entries:
        assert e["ours"].get("fire") in FIRE_TYPES, f'{e["key"]}: ours.fire must be arc, direct or null'


def show(entries):
    lines = []
    for e in entries:
        card, profile = e["card"], e["card"]["profile"]
        name = card["details"].get("Name")
        lines.append(f'## {name if isinstance(name, str) and not name.startswith("unknown:") else e["key"]}')
        lines.append(f'`{e["key"]}` · card {card["date"]}, {card.get("game_version")}\n')
        lines.append("| Stat | Value | Base |\n|---|---|---|")
        stats = card["stats"]
        if "unavailable" in stats:
            lines.append(f'| card | unavailable: {stats["unavailable"]} | |')
        for key, s in stats.items():
            lines.append(f'| {key} | {s["displayed"] if s["displayed"] is not None else s["value"]} | {s["base"]} |')
        lines.append("")
        lines.append(f'Men {profile.get("initial_number_of_men")} · walk {profile.get("slow_speed")} m/s · '
                     f'run {profile.get("fast_speed")} m/s · range {profile.get("missile_range")} m · '
                     f'ammo {profile.get("starting_ammo")} · class {profile.get("unit_class")} · '
                     f'mass {card["details"].get("Mass")} · health {card["details"].get("HealthMax")} · '
                     f'fire (ours) {e["ours"].get("fire")}\n')
        if e["formation"].get("widths"):
            lines.append("| Ordered width, m | Front × depth, m | Reform, s | Ended |\n|---|---|---|---|")
            for w in e["formation"]["widths"]:
                lines.append(f'| {w["ordered_m"]} | {w.get("front_m")} × {w.get("depth_m")} | {w.get("reform_s")} | '
                             f'{w.get("ended")} |')
            lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("scenario")
    up = sub.add_parser("update")
    up.add_argument("events", type=Path)
    sub.add_parser("show")
    args = parser.parse_args(argv)
    sys.stdout.reconfigure(encoding="utf-8")  # names and × in a cp1251 console
    if args.command == "scenario":
        spec = write_scenario()
        print(f"{SCENARIO} ({len(spec['units'])} units)")
    elif args.command == "update":
        for path in update(args.events):
            print(path)
        check(load_roster())
    else:
        entries = load_roster()
        check(entries)
        print(show(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
